name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: |
          echo "Running tests with coverage"
          npm run test:coverage
          echo "Completed tests with coverage"

      - name: Lint
        run: |
          echo "Running linter"
          npm run lint
          echo "Completed linting"

      - name: Build
        run: |
          echo "Building project"
          npm run build
          echo "Build completed"

      - name: Check vulnerabilities
        run: |
          echo "Checking for vulnerabilities"
          npm audit --audit-level=high
          echo "Completed vulnerability check"

        env:
          CI: true
